# Default values for excalidrawcollab.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

appname: excalidrawcollab

frontend: frontendurl
room: collaborationserverurl
storage: storagebackendurl

# component urls
components:  
  BackendGetAndPostUrl: https://frontendurl/api/scenes/
  StorageBackend: https://storagebackendurl/api/v2
  Collaboration: https://collaborationserverurl

environment:
  type: development

# Cache config
Redis:
  STORAGE_URI: "redis://redis.tns-excalidraw-beta.svc.cluster.local:6379"

replicaCount: 1

image:
  repository: alswl/excalidraw:v0.17.3-fork-b1
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations:
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: excalidraw-beta

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: false
  annotation: {}
  
resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi 

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}
