apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: storage
  annotations:
    route.openshift.io/termination: edge
spec:
  rules:
  - host: {{ .Values.storage | quote }}
    http:
      paths:
      - backend:
          service:
            name: storage
            port:
              number: 8081        
        path: ""
        pathType: ImplementationSpecific
  tls:
  - hosts:
    - {{ .Values.storage | quote }}
    secretName: certs