apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: frontend
  name: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: frontend
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.network/excalidraw-default: "true"
        io.kompose.service: frontend
    spec:
      containers:
        - env:        
            - name: VITE_APP_BACKEND_V2_GET_URLls
              value: {{ .Values.components.BackendGetAndPostUrl | quote }}

            - name: VITE_APP_BACKEND_V2_POST_URL
              value: {{ .Values.components.BackendGetAndPostUrl | quote }} 

            - name: VITE_APP_FIREBASE_CONFIG
              value: '{}'

            - name: VITE_APP_HTTP_STORAGE_BACKEND_URL
              value: {{ .Values.components.StorageBackend | quote }}  

            - name: VITE_APP_STORAGE_BACKEND
              value: http

            - name: VITE_APP_DISABLE_TRACKING=true
              value: true

            - name: VITE_APP_WS_SERVER_URL
              value: {{ .Values.components.Collaboration | quote }}

          image: {{ .Values.image.repository | quote }}
          
          name: frontend
          ports:
            - containerPort: 80
              protocol: TCP
          resources: {}
      restartPolicy: Always
